spring.application.name=demo

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/security}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:0407}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.cache.type=redis

spring.servlet.multipart.max-file-size= 20MB
spring.servlet.multipart.max-request-size= 20MB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:dummy}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:dummy}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
logging.level.org.springframework.security.oauth2=DEBUG

server.forward-headers-strategy=native

spring.web.resources.add-mappings=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:dummy}
spring.mail.password=${MAIL_PASSWORD:dummy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

admin.password.value=${ADMIN_PASSWORD:admin}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dummy}
cloudinary.api-key=${CLOUDINARY_API_KEY:dummy}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:dummy}

cloudinary.cloud-name1=${CLOUDINARY_CLOUD_NAME_1:dummy}
cloudinary.api-key1=${CLOUDINARY_API_KEY_1:dummy}
cloudinary.api-secret1=${CLOUDINARY_API_SECRET_1:dummy}

token.secret.key=${TOKEN_SECRET_KEY:v6yB8mH7K2pL4nJ9R1uV3cX5zQ8wE0rT2yU4iO6pA9sD1fG3hJ5kL7zX9cV0bNmQ}

app.frontend.url=${APP_FRONTEND_URL:http://localhost:3000}