spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/bqmusic
spring.datasource.username=postgres
spring.datasource.password=0407
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size= 20MB
spring.servlet.multipart.max-request-size= 20MB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
spring.security.oauth2.client.registration.google.client-id= 33445469214-bu5domsf1kdou3ejtbcnjkr6a6f8l0ve.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret= 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
spring.security.oauth2.client.registration.google.scope=email,profile
logging.level.org.springframework.security.oauth2=DEBUG
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.web.resources.add-mappings=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dangbao720@gmail.com
spring.mail.password=jmiz fgbd gtzc aysx

cloudinary.cloud-name=dgombuvqi
cloudinary.api-key=514426123264669
cloudinary.api-secret=W4piI_KHaw6kAdc-psLF_-8sqZg

cloudinary.cloud-name1=dgul43waq
cloudinary.api-key1=655317537874651
cloudinary.api-secret1=Z9ECMhhNpEQr-m3OT7YDQCCPuAw

token.secret.key=h2jXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/gk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true