spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/bqmusic
spring.datasource.username=postgres
spring.datasource.password=0407
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size= 20MB
spring.servlet.multipart.max-request-size= 20MB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
spring.security.oauth2.client.registration.google.client-id= ${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret= ${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
logging.level.org.springframework.security.oauth2=DEBUG
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.web.resources.add-mappings=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
admin.password.value=${ADMIN_PASSWORD}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=https://bqmusicbe-production.up.railway.app/login/oauth2/code/google
cloudinary.cloud-name1=${CLOUDINARY_CLOUD_NAME_1}
cloudinary.api-key1=${CLOUDINARY_API_KEY_1}
cloudinary.api-secret1=${CLOUDINARY_API_SECRET_1}

token.secret.key=${TOKEN_SECRET_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true